### PR TITLE
fix: reapply other PRs

### PR DESCRIPTION
**Pull request by merceyz**
Reapply https://github.com/arcanis/TypeScript/pull/5, https://github.com/arcanis/TypeScript/pull/4, and https://github.com/arcanis/TypeScript/pull/3

Blocked by https://github.com/arcanis/TypeScript/pull/6

### CODE REVIEW

**Comment by arcanis** [comment]
Is the PR still draft?

**Comment by merceyz** [comment]
Since it contains https://github.com/arcanis/TypeScript/pull/6 I'd like to get that looked at first

**Comment by arcanis** [comment]
Just merged #6

**Comment by arcanis** [comment]
Thanks for doing this work!

**Pull request merged**
